### ISSUE TITLE
Radio and Check Box Extenders

### ISSUE THREAD

**Issue by shellscape** [appendto/juiceui#1]
asp:RadioButton and
asp:CheckBox.

The server control is assigning the widget name to an attribute of the
web server control:

targetControl.Attributes["data-ui-widget"] = Widget.WidgetName;

On the client the widget name is taken from the rendered element:

var element = $('#' + id),   widgetName =
element.attr('data-ui-widget');

This works in most cases except for the RadioButton and CheckBox server
controls. The &lt;asp:RadioButton&gt; and &lt;asp:CheckBox&gt; will be rendered as
&lt;input id="xx" type="xx"&gt;xxx&lt;/input&gt;&lt;label for="xxx" /&gt;.  If you assign
an attribute to these server controls it renders:

 &lt;span&gt; &lt;input id="xx" type="xx"&gt;xxx&lt;/input&gt;&lt;label for="xxx" /&gt;&lt;/span&gt;.

Herein lies the problem, the &lt;span&gt; is the guy getting the attribute and
the client code assumes the attribute is on the &lt;input&gt; element.

**Comment by john-ayers** [comment]
If we take CheckBox as an example, setting any of the following properties: 
- disabled
- style
- class
- tooltip
- attribute

Will cause the CheckBox to render a span.

Would it be a big change to serialize the widget name to json, that would work for any conceivable scenario. Otherwise you'd have to handle both cases (data-ui-widget on the span or on the input element).

**Comment by shellscape** [comment]
Original reporter confirms fixed with changes for 0.9.1.
